### ISSUE TITLE
Error trying to verify jwk. 

### ISSUE THREAD

**Issue by markmiscavage** [mozilla/mozilla-django-oidc#198] opened 2017-11-17 19:44 UTC
I'm using this package to integrate with a 3rd party OIDC and getting this error during oidc callback. 

AttributeError at /oidc/callback/
'str' object has no attribute 'verifier'

The offending line ` if not jws.verify(jwk): ` in auth.py seems like it has been updated fairly recently in this package. Nothing in the josepy package relating to this seems to have been updated in the last 2 years or more. 

I'm going to dig into this more on my end but wanted to bring it up here to see if anyone had a quick fix off the top of their head. Or can help figure out what I've done wrong in my configuration.

**Comment by brat000012001** [comment] 2017-12-20 00:45
I am running into the same issue.  My settings.py has the following oidc variables defined:
```
OIDC_RP_CLIENT_ID = "someclient"  # os.environ['OIDC_RP_CLIENT_ID']
OIDC_RP_CLIENT_SECRET = "somesecret" # os.environ['OIDC_RP_CLIENT_SECRET']
OIDC_RP_IDP_SIGN_KEY="<base64 encoded public key>"
OIDC_RP_SIGN_ALGO="RS256"
```
The callstack is shown below:
```
local/lib/python2.7/site-packages/josepy/jwa.py in verify
123                    verifier = key.verifier(sig, self.padding, self.hash) 
local/lib/python2.7/site-packages/josepy/jws.py in verify
198                        msg=self._msg(self.protected, payload)) 
local/lib/python2.7/site-packages/josepy/jws.py in <genexpr>
261                    return all(sig.verify(self.payload, key) for sig in self.signatures) 
local/lib/python2.7/site-packages/mozilla_django_oidc/auth.py in _verify_jws
95                    if not jws.verify(jwk): 
local/lib/python2.7/site-packages/mozilla_django_oidc/auth.py in verify_token
123                        smart_bytes(key), 
local/lib/python2.7/site-packages/mozilla_django_oidc/auth.py in authenticate
174                    if self.verify_token(id_token, nonce=nonce): 
local/lib/python2.7/site-packages/django/contrib/auth/__init__.py in authenticate
74                        user = backend.authenticate(**credentials) 
local/lib/python2.7/site-packages/mozilla_django_oidc/views.py in get
75                        self.user = auth.authenticate(**kwargs) 
...
```

**Comment by johnpaulett** [comment] 2017-12-20 00:58
I have not finished investigating, but I was having this issue with Auth0 when it returned an RS256 token, but I was using the default HS256 in `OIDC_RP_SIGN_ALGO`.  Changing to OIDC_RP_SIGN_ALGO to RS256 and creating a PEM version of the signing key seemed to resolve it.  I have not yet tried changing the signing algorithm in the Auth0 control panel.

@brat000012001 are you sure you are getting an RS256 token back and not an HS256 key (inverse of what what happening to me)? 

I hope to have some more details in the next few days. If this is the issue, it appears to be common enough that raising a more explicit exception may be helpful.

**Comment by brat000012001** [comment] 2017-12-20 01:27
@johnpaulett Yep, I can confirm that changing SIGN_KEY to a properly formatted PEM public key got me further, i.e. I am no longer getting the aforementioned exception. I am still having issues with getting the user properly (the statement {% if user.is_authenticated %} returns false even after what appears to be a successful login), but at least I am not crashing in callback.

**Comment by johngian** [comment] 2018-02-09 11:04
I think that the issue here was mainly caused because:

* The docs don't explain in detail how to configure RS-based RPs
* At some point we changed the way we configure RS-based credentials because we switched to ``josepy`` which required a PEM formatted key.
 
For end-to-end testing we are using a ``testrp`` docker image which is pretty much a test django app with ``mozilla-django-oidc`` as authentication backend.

We already run tests against this test app so we know that both ``HS`` and ``RS`` configuration works. I am going to export a ``./manage.py diffsettings`` and add the OIDC related entries to our docs as example setups.

Do you think that's going to be useful ?

**Comment by markmiscavage** [comment] 2018-02-09 16:50
Yes, a better example should help quite a bit.

I was ultimately able to get my implementation of this project working, it just took some extra communication between myself and the OIDC provider I was authing with to figure out the correct set of settings we needed.

**Comment by bostrick** [comment] 2018-02-15 02:44
I think the problem here is really in josepy....

https://github.com/certbot/josepy/blob/master/src/josepy/jwk.py#L107

```python
        try:
            key = cls._load_cryptography_key(data, password, backend)
        except errors.Error as error:
            logger.debug('Loading symmetric key, asymmetric failed: %s', error)
            return JWKOct(key=data)
```

where, despite the function description above it to the contrary, if it can't load the data as a public key it dubiously falls back to loading it as a symmetric key, which should always "work" but often not meaningfully.

Subsequent mozilla-django-oidc code then treats the result as a public key, not knowing any of the wiser...

The upshot is that for any incorrectly formatted public key, the failure doesn't occur until much later and is hard to diagnose.

**Comment by ar-anvd** [comment] 2018-02-15 10:57
Same problem here with google server. There is some workaround?

**Comment by jschwartzentruber** [comment] 2018-04-27 00:51
I had this with auth0 too. I got the the base64 DER cert from https://example.com/.well-known/jwks.json and got the public key as a PEM from openssl (`openssl x509 -inform der -in cert.der -pubkey`) and added this in `settings.py`:
```
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_RP_IDP_SIGN_KEY = """-----BEGIN PUBLIC KEY-----
...
-----END PUBLIC KEY-----
"""
```

**Comment by johngian** [comment] 2018-05-07 17:04
Closing this one after #229 

We added some more documentation when using RS-based signing algorithm and we now also support using JWKS endpoint to receive the key which probably make it easier to integrate.

**Closed by johngian** 2018-05-07 17:04 UTC
