### ISSUE TITLE
Enable OIDC discovery for RPs.

### ISSUE THREAD

**Issue by akatsoulas** [mozilla/mozilla-django-oidc#71] opened 2016-12-20 07:49 UTC

**Comment by gdestuynder** [comment] 2017-05-30 18:28
OIDC Discovery tldr:

OIDC client/RP loads the discovery URL such as https://auth-dev.mozilla.auth0.com/.well-known/openid-configuration and assigning endpoints URLs based on it. This makes it easier to configure endpoints for clients, basically.

**Comment by peterbe** [comment] 2017-05-30 18:42
So what did we have in mind here? (I'm thinking quite a lot about the documentation) 
An RP developer, like me, has a **domain** and I can append `/.well-known/openid-configuration` and study that JSON with my eyes and try to figure out what the URLs should be. 

Would it be an option to add a management command, like: `./manage.py discover-oidc-urls mydomain.auth0.com` that spits out the right URLs to put into my `settings.py`?

**Comment by peterbe** [comment] 2017-05-30 18:42
At least we could start with adding the trick of `GET mydomain + /.well-known/openid-configuration` to the documentation.

**Comment by peterbe** [comment] 2017-05-30 18:47
Heck, what about setting `OIDC_OP_DOMAIN = "mydomain.auth0.com"` in `settings.py` and it could just do everything else. 
Perhaps something like this:

```python
authorization_url = getattr(settings, 'OIDC_OP_AUTHORIZATION_ENDPOINT', None)
if not authorization_url:
    logger.info(
        'No settings.OIDC_OP_AUTHORIZATION_ENDPOINT so guessing URL '
        'based on settings.OIDC_OP_DOMAIN instead.'
    )
    authorization_url = 'https://{}/authorize'.format(settings.OIDC_OP_DOMAIN)
```

**Comment by gdestuynder** [comment] 2017-05-30 21:32
the last comment => yes :)
Also spec: http://openid.net/specs/openid-connect-implicit-1_0.html#SelfIssuedDiscovery

**Comment by johngian** [comment] 2019-08-02 14:19
Closing this one as a duplicate of #280

**Closed by johngian** 2019-08-02 14:19 UTC
