### ISSUE TITLE
Please release a new version to PyPi

### ISSUE THREAD

**Issue by pauloxnet** [mozilla/mozilla-django-oidc#338] opened 2020-01-02 14:33 UTC
Now the package is not usable with Django 3.0 but the commit with the fix was pushed one month ago:
https://github.com/mozilla/mozilla-django-oidc/commit/ab37be7ae2d47a7a3e90b4783c9493160ce8e3ae

Can you release a new version of this package on PyPi so we can continue using with the latest version of Django?

If I can help doing this I'm ready.

**Comment by willkg** [comment] 2020-01-02 14:40
The commit was made a while ago, but the PR it contained was merged 2 hours ago as of this writing:

https://github.com/mozilla/mozilla-django-oidc/pull/336

I'm sure they're working on a release soon. Closing this out because it's a duplicate of #333 and other issues covering "support Django 3.0".

**Closed by willkg** 2020-01-02 14:40 UTC

**Comment by johngian** [comment] 2020-01-02 14:42
Hey, for now you can use `master`, i am planning to do a release soon.

**Comment by alcad** [comment] 2020-01-02 14:46
Hi @pauloxnet and @willkg ,
I've same need.
Upgraded django but trouble with mozilla-django-oidc.
I wait for a PyPi package release

Best regards

**Comment by pauloxnet** [comment] 2020-01-02 14:47
Thanks, I've checked only the opened issue before adding this one but the #333 is closed so I've missed it.

I'm using `master` right now but a new release on pypi will be very useful.

Thanks for the quick reply and your work on this packages and this specific issue, I appreciate it a lot.

**Comment by johngian** [comment] 2020-01-02 16:01
FYI `v1.2.3` is released on PyPI
https://pypi.org/project/mozilla-django-oidc/1.2.3/

**Comment by pauloxnet** [comment] 2020-01-02 16:20
Thank you very much

**Comment by alcad** [comment] 2020-01-02 16:23
Thank you @johngian
