### ISSUE TITLE
Feature request: support RS256 as signing algorithm

### ISSUE THREAD

**Issue by hmpf** [mozilla/mozilla-django-oidc#149] opened 2017-06-14 06:03 UTC
mozilla-django-oidc cannot be used with the provider [Dataporten](https://auth.dataporten.no/.well-known/openid-configuration) as it does not support RS256.

Currently you wind up with a 500 error due to the following exception being raised:

```
JWSError at /oidc/callback/

The specified alg value is not allowed
```

**Comment by maikhoepfel** [comment] 2017-06-28 14:10
I suggest closing this as a duplicate of https://github.com/mozilla/mozilla-django-oidc/issues/70.

**Comment by maikhoepfel** [comment] 2017-06-28 14:15
This unfortunately also happens with Microsoft's ADFS OIDC integration. I managed to reproduce it locally with an instance of Keycloak where one can enforce signing with RS256. `python-jose` luckily supports RS256, so I hope the needed changes are manageable. 

I might be able to look at this. Is RS256 support something you would merge?

**Comment by johngian** [comment] 2017-06-30 16:56
@hmpf Yeah definitely. PRs are welcome :+1:

**Comment by maikhoepfel** [comment] 2017-06-30 17:42
I set the allowed protocol from  `'HS256'` to `'RS256'` in `mozilla-django-oidc`, which unfortunately triggers a failure with any of the three crypto backends in `python-jose`. I did not know how to proceed beyond that point. 

I gave up and went with https://github.com/py-pa/django-oidc instead.

**Comment by puiterwijk** [comment] 2017-07-14 11:03
@maikhoepfel Did you also change the key that it uses? Since with HS256, the client secret is used for the HMAC, whereas with RS256, the provider uses a JWK RSA key to sign.
If you want to, you could try my patch out in #161, since that implementation works well for me.

**Comment by maikhoepfel** [comment] 2017-07-27 10:00
@puiterwijk I didn't know - I really don't know my way 'round crypto. The patch looks great and thanks for reaching out - but I have since switched clients.

**Comment by audrummer15** [comment] 2017-08-30 19:18
Any movement on this? I see the PR has stalled... This breaks Google's authentication as well

**Comment by codytodonnell** [comment] 2017-09-28 20:50
Experiencing the same problem with my company's auth system

**Closed** 2017-10-02 15:29 UTC
