### ISSUE TITLE
jws.verify() returns a byte string

### ISSUE THREAD

**Issue by peterbe** [mozilla/mozilla-django-oidc#116] opened 2017-05-30 19:41 UTC
I'm currently getting this error:
```
web_1          | Traceback (most recent call last):
web_1          |   File "/usr/local/lib/python3.5/wsgiref/handlers.py", line 137, in run
web_1          |     self.result = application(self.environ, self.start_response)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
web_1          |     return self.application(environ, start_response)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/wsgi.py", line 157, in __call__
web_1          |     response = self.get_response(request)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 124, in get_response
web_1          |     response = self._middleware_chain(request)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 43, in inner
web_1          |     response = response_for_exception(request, exc)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 93, in response_for_exception
web_1          |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
web_1          |     response = get_response(request)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
web_1          |     response = self._get_response(request)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
web_1          |     response = self.process_exception_by_middleware(e, request)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
web_1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
web_1          |     return self.dispatch(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
web_1          |     return handler(request, *args, **kwargs)
web_1          |   File "/usr/local/lib/python3.5/site-packages/mozilla_django_oidc/views.py", line 59, in get
web_1          |     self.user = auth.authenticate(**kwargs)
web_1          |   File "/usr/local/lib/python3.5/site-packages/django/contrib/auth/__init__.py", line 100, in authenticate
web_1          |     user = backend.authenticate(*args, **credentials)
web_1          |   File "/usr/local/lib/python3.5/site-packages/mozilla_django_oidc/auth.py", line 121, in authenticate
web_1          |     if self.verify_token(id_token, nonce=nonce):
web_1          |   File "/usr/local/lib/python3.5/site-packages/mozilla_django_oidc/auth.py", line 82, in verify_token
web_1          |     token_nonce = json.loads(verified_token).get('nonce')
web_1          |   File "/usr/local/lib/python3.5/json/__init__.py", line 312, in loads
web_1          |     s.__class__.__name__))
web_1          | TypeError: the JSON object must be str, not 'bytes'
```

It happens because of these lines:
https://github.com/mozilla/mozilla-django-oidc/blob/fa202c92a5317b2dc66d77861aebd4c0df340449/mozilla_django_oidc/auth.py#L87-L88

The `verified_token` variable becomes a byte string (Python 3.5 in my docker). E.g. `b'{"iss":"https://auth.mozilla.auth0.com/","sub":"a...`

Can you can't send in a byte string to `json.loads()`.

**Comment by peterbe** [comment] 2017-05-30 19:42
For what it's worth, variables `token` and `secret` (both which are passed into `jws.verify` are regular strings (i.e. unicode).

**Comment by peterbe** [comment] 2017-05-30 19:59
It might be a bug in `python-jose`. See [the doc string for `jws.verify`](https://github.com/mpdavis/python-jose/blob/7403dffbf9d8980c43c9ea40e4c580035d7b2fce/jose/jws.py#L60)
It says the payload is supposed to be a `str`. 

However, the `payload` is ultimately coming from [here](https://github.com/mpdavis/python-jose/blob/7403dffbf9d8980c43c9ea40e4c580035d7b2fce/jose/jws.py#L196) which is, ultimately, the output of calling `base64.urlsafe_b64decode` which in Python 3 *always* returns a byte string. 

```python
>>> base64.urlsafe_b64decode('cGV0ZXI=')
b'peter'
>>> base64.urlsafe_b64decode(b'cGV0ZXI=')
b'peter'
```

So I think we need to account for this when we send the payload to `json.loads`.

**Comment by willkg** [comment] 2017-05-30 20:03
Are you setting `OIDC_RP_CLIENT_SECRET_ENCODED` ?

**Comment by peterbe** [comment] 2017-05-30 20:08
> Are you setting OIDC_RP_CLIENT_SECRET_ENCODED ? 

No.

**Comment by peterbe** [comment] 2017-05-30 20:12
Apparently, in Python 3.6 you will be able to send a byte string to `json.loads`
https://bugs.python.org/issue10976
Till then we need a solution.

**Comment by willkg** [comment] 2017-05-30 20:14
Ahh... ok. I'm using Python 3.6 so I'm not seeing this. I thought maybe this was a dupe of #89.

**Comment by peterbe** [comment] 2017-05-30 20:16
So close in the code in terms of number-of-lines-away but indeed different. 

To make myself unstuck and being able to log in at all in my docker life, I edit the code inside `mozilla_django_oidc/auth.py` :)

**Closed** 2017-05-31 14:58 UTC
