### ISSUE TITLE
OIDC Callback

### ISSUE THREAD

**Issue by Cwei1** [mozilla/mozilla-django-oidc#412] opened 2021-03-31 19:22 UTC
I am getting an error SuspiciousOperation at /oidc/callback/

OIDC callback state not found in session 'oidc_states'

What could be the probable cause of this?

Thanks!

**Comment by akatsoulas** [comment] 2022-05-30 15:35
Duplicate of #435

**Closed by akatsoulas** 2022-05-30 15:35 UTC
